tap "brimdata/tap"
tap "cantino/mcfly"
tap "federico-terzi/espanso"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "neovim/neovim"
tap "osx-cross/arm"
tap "osx-cross/avr"
brew "actionlint"
brew "openssl@3"
brew "readline"
brew "sqlite"
brew "xz"
brew "ansible"
brew "awscli"
brew "bat"
brew "bluetoothconnector"
brew "gettext"
brew "glib"
brew "capstone"
brew "colordiff"
brew "coreutils"
brew "curl"
brew "curlie"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "dog"
brew "duf"
brew "dust"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "foreman"
brew "fx"
brew "fzf"
brew "gat"
brew "gawk"
brew "gh"
brew "ghq"
brew "gifsicle"
brew "gist"
brew "git"
brew "git-delta"
brew "git-secrets"
brew "glances"
brew "pinentry"
brew "gnupg"
brew "go"
brew "graphviz"
brew "grep"
brew "gron"
brew "gti"
brew "hexyl"
brew "highlight"
brew "htop"
brew "httpie"
brew "hub"
brew "hyperfine"
brew "shared-mime-info"
brew "imagemagick"
brew "iproute2mac"
brew "jemalloc"
brew "jq"
brew "jql"
brew "libffi"
brew "lima"
brew "lsd"
brew "lv"
brew "mackup"
brew "mas"
brew "mise"
brew "neofetch"
brew "neovim"
brew "nkf"
brew "packer"
brew "peco"
brew "pinentry-mac"
brew "procs"
brew "pulumi"
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "ripgrep-all"
brew "rust"
brew "sd"
brew "shellcheck"
brew "ssh-copy-id"
brew "starship"
brew "subversion"
brew "switchaudio-osx"
brew "tailspin"
brew "tealdeer"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tmuxinator"
brew "tokei"
brew "tree"
brew "vim"
brew "walk"
brew "wget"
brew "yt-dlp"
brew "zellij"
brew "zoxide"
brew "cantino/mcfly/mcfly"
brew "federico-terzi/espanso/espanso"
brew "heroku/brew/heroku"
cask "1password"
cask "alacritty"
cask "alfred"
cask "altair-graphql-client"
cask "amorphousdiskmark"
cask "appcleaner"
cask "appzapper"
cask "arctype"
cask "audio-hijack"
cask "aws-vault"
cask "barrier"
cask "bartender"
cask "bettertouchtool"
cask "betterzip"
cask "brave-browser"
cask "cheatsheet"
cask "choosy"
cask "cursor"
cask "cyberduck"
cask "discord"
cask "dynalist"
cask "fig"
cask "firefox"
cask "fluent-reader"
cask "flux"
cask "folx"
cask "font-biz-udgothic"
cask "font-biz-udmincho"
cask "font-biz-udpgothic"
cask "font-biz-udpmincho"
cask "font-cica"
cask "font-fira-code"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "font-ibm-plex"
cask "font-mplus"
cask "font-mplus-nerd-font"
cask "font-myrica"
cask "font-noto-sans-cjk-jp"
cask "font-noto-serif-cjk-jp"
cask "font-ricty-diminished"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-udev-gothic-nf"
cask "github"
cask "google-chrome"
cask "hyperswitch"
cask "iina"
cask "iterm2"
cask "joplin"
cask "kap"
cask "karabiner-elements"
cask "keka"
cask "kitty"
cask "ksdiff"
cask "libreoffice"
cask "loopback"
cask "megasync"
cask "notion"
cask "obsidian"
cask "onyx"
cask "opera"
cask "raindropio"
cask "rectangle"
cask "script-debugger"
cask "sensei"
cask "session-manager-plugin"
cask "signal"
cask "skype"
cask "spotify"
cask "stats"
cask "steam"
cask "switchhosts"
cask "tableplus"
cask "via"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "warp"
cask "wave"
cask "wezterm"
cask "wkhtmltopdf"
cask "xld"
cask "xquartz"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "BetterSnapTool", id: 417375580
mas "Cardhop", id: 1290358394
mas "Cloud Battery", id: 1481005137
mas "CotEditor", id: 1024640650
mas "DaisyDisk", id: 411643860
mas "Display Menu", id: 549083868
mas "EdgeView 2", id: 1206246482
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "Gyazo", id: 490085255
mas "Hex Fiend", id: 1342896380
mas "iMovie", id: 408981434
mas "isHUD", id: 484757536
mas "Jayson", id: 1468691718
mas "Kaleidoscope", id: 587512244
mas "Keepa - Price Tracker", id: 1533805339
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Noizio", id: 928871589
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PhoneCast", id: 1548183660
mas "Pixelmator Pro", id: 1289583905
mas "Pocket", id: 568494494
mas "Remote Desktop", id: 409907375
mas "RunCat", id: 1429033973
mas "Save to Pocket", id: 1477385213
mas "Save to Raindrop.io", id: 1549370672
mas "Slack", id: 803453959
mas "Snippety", id: 1530751461
mas "StuffIt Expander", id: 919269455
mas "Trello", id: 1278508951
mas "Tunacan", id: 980577198
mas "TweetDeck", id: 485812721
mas "Twitter", id: 1482454543
mas "Whisper", id: 1668083311
mas "WiFi Explorer", id: 494803304
mas "WiFi Signal", id: 525912054
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
mas "辞書 by 物書堂", id: 1380563956
