tap "cantino/mcfly"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "readline"
brew "xz"
brew "asdf"
brew "awscli"
brew "bat"
brew "colordiff"
brew "curl"
brew "direnv"
brew "exa"
brew "fish"
brew "gh"
brew "ghq"
brew "gist"
brew "git"
brew "pinentry"
brew "gnupg"
brew "iproute2mac"
brew "lv"
brew "mackup"
brew "mas"
brew "peco"
brew "pinentry-mac"
brew "reattach-to-user-namespace"
brew "ssh-copy-id"
brew "tig"
brew "tmux"
brew "vim"
brew "wget"
brew "zoxide"
brew "cantino/mcfly/mcfly"
cask "1password"
cask "alacritty"
cask "alfred"
cask "appcleaner"
cask "appzapper"
cask "aws-vault"
cask "bartender"
cask "betterzip"
cask "brave-browser"
cask "dash"
cask "firefox"
cask "font-cica"
cask "font-fira-code"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "font-mplus"
cask "font-mplus-nerd-font"
cask "font-myrica"
cask "font-ricty-diminished"
cask "font-roboto"
cask "font-source-code-pro"
cask "github"
cask "google-chrome"
cask "hyperswitch"
cask "iterm2"
cask "joplin"
cask "karabiner-elements"
cask "kitty"
cask "megasync"
cask "obsidian"
cask "rectangle"
cask "sensei"
cask "session-manager-plugin"
cask "visual-studio-code"
cask "xquartz"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "CotEditor", id: 1024640650
mas "EdgeView 2", id: 1206246482
mas "Fantastical", id: 975937182
mas "isHUD", id: 484757536
mas "Kaleidoscope", id: 587512244
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
